services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proxy-net

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_KEY_PREFIX=v1
      - API_PORT=8080
    depends_on:
      - redis
    networks:
      - proxy-net

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_KEY_PREFIX=v1
      - REDIS_TOPIC_VERIFY=proxies:verify
      - SCRAPE_INTERVAL_MINUTES=1 # Fast interval for testing
    depends_on:
      - redis
    networks:
      - proxy-net

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    deploy:
      replicas: 2
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_KEY_PREFIX=v1
      - REDIS_TOPIC_VERIFY=proxies:verify
      - REDIS_GROUP_WORKERS=verifiers
      - CONSUMER_NAME_PREFIX=worker # Will allow us to differentiate logs if we log hostname
    depends_on:
      - redis
    networks:
      - proxy-net

volumes:
  redis_data:

networks:
  proxy-net:
    driver: bridge
