with-expecter: true
packages:
  github.com/JulianoL13/app-proxy-engine/internal/verifier:
    config:
      dir: internal/verifier/mocks
      outpkg: mocks
    interfaces:
      ProxyChecker:
        config: {}
      Verifiable:
        config: {}
      Consumer:
        config: {}
      Writer:
        config: {}
      ProxyDeserializer:
        config: {}
      VerifiedProxy:
        config: {}
      WorkerPool:
        config: {}
  github.com/JulianoL13/app-proxy-engine/internal/scraper:
    config:
      dir: internal/scraper/mocks
      outpkg: mocks
    interfaces:
      Fetcher:
        config: {}
      Publisher:
        config: {}
      ProxyScraper:
        config: {}
      ProxySerializer:
        config: {}
      Cleaner:
        config: {}
      ScrapedProxy:
        config: {}
  github.com/JulianoL13/app-proxy-engine/internal/proxy:
    config:
      dir: internal/proxy/mocks
      outpkg: mocks
    interfaces:
      Reader:
        config: {}
  github.com/JulianoL13/app-proxy-engine/internal/proxy/http:
    config:
      dir: internal/proxy/http/mocks
      outpkg: mocks
    interfaces:
      GetProxiesUseCase:
        config: {}
      GetRandomProxyUseCase:
        config: {}
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
